language: go

env:
  - GO15VENDOREXPERIMENT=1

go:
  - 1.5
  - 1.6
  - tip

before_install:
   # Install Kafka
   - wget http://www.us.apache.org/dist/kafka/0.8.2.1/kafka_2.10-0.8.2.1.tgz -O kafka.tgz
   - mkdir -p kafka && tar xzf kafka.tgz -C kafka --strip-components 1
   - cd kafka
   # Run Zookeeper/Kafka on localhost (default ports for ZK, Kafka: 2181, 9092)
   - ./bin/zookeeper-server-start.sh config/zookeeper.properties &
   - sleep 3
   - ./bin/kafka-server-start.sh config/server.properties &
   - sleep 5
   # Create 'zipkin' topic with 1 partitions
   - ./bin/kafka-topics.sh --zookeeper localhost:2181 --create --topic zipkin --partitions 1 --replication-factor 1
   - cd ../

install:
  - go get git.apache.org/thrift.git/lib/go/thrift
  - go get github.com/Shopify/sarama
  - go get github.com/Sirupsen/logrus
  - go get github.com/elodina/go-avro
  - go get github.com/51idc/go-zipkin
  - go build -v

script: go test -v ./...
