language: go

env:
  - GO15VENDOREXPERIMENT=1

go:
  - 1.5
  - 1.6
  - tip

install:
  - go get git.apache.org/thrift.git/lib/go/thrift
  - go get github.com/Shopify/sarama
  - go get github.com/Sirupsen/logrus
  - go get github.com/elodina/go-avro
  - go get github.com/51idc/go-zipkin
  - go build -v

script: go test -v ./...
